FROM node:18-alpine

RUN apk add --no-cache tzdata
ENV TZ=Europe/Warsaw

WORKDIR /app

COPY package.json yarn.lock /app/

RUN yarn install --frozen-lockfile

COPY . /app/

ENV SUMMARY_MODE cron
ENTRYPOINT [ "./docker-entrypoint.sh" ]
